fixing problem with transforming crs for requesting time stamps. see …
dcs4cop/xcube-sh pull request #62
Opened 2021-07-26 09:42 UTC by AliceBalfanz

fixing problem with transforming crs for requesting time stamps. see investigation documentation in issue #60

2021-07-26 11:37 UTC, AliceBalfanz commented
Only failing test is https://github.com/dcs4cop/xcube-sh/blob/master/test/test_reprod_27.py 

therefor I am reopening the related issue: 
https://github.com/dcs4cop/xcube-sh/issues/27

2021-07-29 09:29 UTC, TonioF reviewed
Please see comments.

2021-07-29 09:29 UTC, TonioF commented on xcube_sh/sentinelhub.py
> +                # True if CRS is in geocentric (x/y) coordinates, whereas WGS84 is geodetic (y/x)
Please heed maximum line number of 80 characters, also for docs and comments.

2021-07-29 09:29 UTC, TonioF commented on xcube_sh/sentinelhub.py
> +                if not source_crs.axis_info[0].unit_name == 'degree':
I think this is a very unfortunate way to do your check. Can't you use 'is_geographic'?

2021-07-29 09:29 UTC, TonioF commented on xcube_sh/sentinelhub.py
> +                    (x1, x2), (y1, y2) = transformer.transform((x1, x2), (y1, y2))
Can you add a test that goes here? I didn't find one.

2021-07-30 09:58 UTC, TonioF approved these changes

2021-08-06 10:17 UTC, forman requested changes
Looks good, thanks! Please update `CHANGES.md` accordingly.

2021-08-06 11:34 UTC, forman approved these changes

2021-08-06 11:35 UTC, merged